### PR TITLE
added legend to map

### PR DESCRIPTION
**Pull request by lauradumi**

### CODE REVIEW

**Comment by lauradumi** [comment]
[Add legend to map](https://trello.com/c/9Vwbz6JI/75-add-legend-to-map)

**Comment by lauradumi** [comment]
Added round colored buttons as legend and changed provigo store url for a horizontal image to fit map popup. 

Screen Shot 2024-06-11 at 22 42 28
Screen Shot 2024-06-11 at 22 43 16

**Comment by lauradumi** [comment]
and made price more prominent
Screen Shot 2024-06-11 at 22 46 50

**Review by chrononaut76 — APPROVED** [review]
LGTM

**Pull request merged**
