### PR TITLE
updated seed file

### PR DESCRIPTION
**Pull request by lauradumi**
Added more stores to the seed and changed the price range because to get a higher total price result. The totals we were getting for the stores were too low and unrealistic. 

I've also added a real image url to the seed file to be able to add the image to the store card

Screen Shot 2024-06-03 at 23 16 14
Screen Shot 2024-06-03 at 23 16 28

### CODE REVIEW

**Comment by lauradumi** [comment]
[update seed file with more stores and fix prices for a more realistic total](https://trello.com/c/ytaz6A31/65-update-seed-file-with-more-stores-and-fix-prices-for-a-more-realistic-total)

**Comment by lauradumi** [comment]
I just realized that I only changed the price range in the seed file but not in the private method within the application controller which gets called during the query, so I will have to fix that

**Review by chrononaut76 — DISMISSED** [review]
Approved. Please merge.

**Review by chrononaut76 — APPROVED** [review]
Approved

**Pull request merged**
